image: alpine

before_script:
  - 'which ssh-agent || ( apk add openssh )'
  - apk add git
  - eval $(ssh-agent -s)

stages:
  - deploy
staging_deploy:
  stage: deploy
  script:
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan 15.188.246.27 >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    - git remote remove consul || true
    - git remote add consul dokku@15.188.246.27:consul || true
    - git push consul develop:master
  only:
    - develop
  when: manual

production_deploy:
  stage: deploy
  script:
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan 15.188.246.27 >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    - git remote remove consul || true
    - git remote add consul dokku@10.24.0.2:consul || true
    - git push consul origin/master:master
  only:
    - master
  when: manual
