default: &default
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  email_interceptor_recipients: ""

maps: &maps
  map_tiles_provider: "//{s}.tile.openstreetmap.org/{z}/{x}/{y}.png"
  map_tiles_provider_attribution: "&copy; <a href=\"http://osm.org/copyright\">OpenStreetMap</a> contributors"

apis: &apis
  microsoft_api_key: ""
  census_api_end_point: ""
  census_api_institution_code: ""
  census_api_portal_name: ""
  census_api_user_code: ""
  sms_end_point:  ""
  sms_username: ""
  sms_password: ""

http_basic_auth: &http_basic_auth
  http_basic_auth: true

development:
  http_basic_username: ""
  http_basic_password: ""
  auth0_key:  <%= ENV["AUTH0_KEY"] %>
  auth0_secret: <%= ENV["AUTH0_SECRET"] %>
  auth0_domain: <%= ENV["AUTH0_DOMAIN"] %>
  <<: *default
  <<: *maps

test:
  <<: *default
  <<: *maps

staging:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  server_name: <%= ENV["SERVER_NAME"] %>
  # mailer_delivery_method: :smtp
  # smtp_settings:
  #   :address: "smtp.example.com"
  #   :port: 25
  #   :domain: "your_domain.com"
  #   :user_name: "<username>"
  #   :password: "<password>"
  #   :authentication: "plain"
  #   :enable_starttls_auto: true
  force_ssl: true
  delay_jobs: true
  rollbar_server_token: ""
  http_basic_username: ""
  http_basic_password: ""
  managers_url: ""
  managers_application_key: ""
  auth0_key:  <%= ENV["AUTH0_KEY"] %>
  auth0_secret: <%= ENV["AUTH0_SECRET"] %>
  auth0_domain: <%= ENV["AUTH0_DOMAIN"] %>
  <<: *default
  <<: *maps
  <<: *apis

production:
  secret_key_base: ""
  server_name: ""
  # mailer_delivery_method: :smtp
  # smtp_settings:
  #   :address: "smtp.example.com"
  #   :port: 25
  #   :domain: "your_domain.com"
  #   :user_name: "<username>"
  #   :password: "<password>"
  #   :authentication: "plain"
  #   :enable_starttls_auto: true
  force_ssl: true
  delay_jobs: true
  rollbar_server_token: ""
  http_basic_username: ""
  http_basic_password: ""
  managers_url: ""
  managers_application_key: ""
  twitter_key: ""
  twitter_secret: ""
  facebook_key: ""
  facebook_secret: ""
  google_oauth2_key: ""
  google_oauth2_secret: ""
  wordpress_oauth2_key: ""
  wordpress_oauth2_secret: ""
  wordpress_oauth2_site: ""
  auth0_key:  <%= ENV["AUTH0_KEY"] %>
  auth0_secret: <%= ENV["AUTH0_SECRET"] %>
  auth0_domain: <%= ENV["AUTH0_DOMAIN"] %>
  <<: *maps
  <<: *apis
